### ISSUE TITLE
dependency upgrade

### ISSUE THREAD

**Issue by clragon** [gbwisx/msal_mobile#12]
The version of `flutter_cache_manager` this plugin depends on has been outdated for a while.
This causes issues with other plugins that have upgraded to the newer version.

Namely, I encountered 
`msal_mobile 0.1.4 depends on flutter_cache_manager ^1.1.3`
and 
`cached_network_image >=2.5.0 depends on flutter_cache_manager ^2.1.0`

**Comment by JediIzzyT** [comment]
I believe that issue #17 repeats this issue. I am also experiencing issues here that are forcing me to use older versions of packages that I need, or to skip them entirely. This is the error that I'm getting:

```
Because no versions of msal_mobile match >0.1.4 <0.2.0 and msal_mobile 0.1.4 depends on flutter_cache_manager ^1.1.3, msal_mobile ^0.1.4 requires flutter_cache_manager ^1.1.3.
Because flutter_cache_manager >=1.2.0 <2.0.0-beta depends on path_provider ^1.4.0 and flutter_cache_manager >=1.0.0 <1.2.0 depends on path_provider >=0.5.0 <2.0.0, flutter_cache_manager >=1.0.0 <2.0.0-beta requires path_provider >=0.5.0 <2.0.0.
Thus, msal_mobile ^0.1.4 requires path_provider >=0.5.0 <2.0.0.
So, because <my_app_name> depends on both msal_mobile ^0.1.4 and path_provider ^2.0.1, version solving failed.
pub get failed (1; So, because <my_app_name> depends on both msal_mobile ^0.1.4 and path_provider ^2.0.1, version solving failed.)
```

**Comment by clragon** [comment]
we cant really fix this without the maintainer of the package stepping in and doing something.

I guess we could upgrade the packages ourselves and provide a PR to accelerate things, perhaps.
